### ISSUE TITLE
multiple deserializers

### ISSUE THREAD

**Issue by omaraboumrad** [Link-/pyboiler#6]
Make structure building flexible by allowing multiple means/methods of deserialising:
### Option - 1: JSON (Current)

Uses the built-in JSON serializer
## Option - 2: Yaml

This option is available only if the package `PyYAML` is installed.

Example:

```
Project:
    - name: base
      children:
          - name: src
            children:
                - name: hello.py
                  type: file 
    - name: build
      children:
          - name: lib
            type: folder
    - name: README.md
      type: file
```
## Option - 3: Indented text file

This option should be available by default and allows input from an indented
text file.

Example:

```
base
    src
        hello.py fi
    build
        lib fo
    README.md fi
```
## Option - 4: (Extension to Option - 3, through heredoc)

```
% pyboiler << EOF
    base
        src
            hello.py fi
        build
            lib fo
        README.md fi
EOF
```

---

In complement to the above, add a test suite with fixture tests covering the above options.
